# Generated by Django 4.0.3 on 2022-04-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sub_plan_name',
            field=models.CharField(max_length=100),
        ),
    ]
